//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donation
    {
        public int DonationsID { get; set; }
        public System.DateTime Donatdate { get; set; }
        public string Place { get; set; }
        public string FK_Donation_ID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
