//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donor
    {
        public int D_ID { get; set; }
        public Nullable<int> D_NoDonations { get; set; }
        public string D_candonate { get; set; }
        public string FK_donor_ID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
