//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostRequest
    {
        public int Request_ID { get; set; }
        public string BloodGroup { get; set; }
        public int Address { get; set; }
        public string Status { get; set; }
        public string FK_ID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual GoogleMap GoogleMap { get; set; }
    }
}
