//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisteredUser
    {
        public int R_ID { get; set; }
        public string R_Email { get; set; }
        public string R_Name { get; set; }
        public string R_Gender { get; set; }
        public string R_BloodGroup { get; set; }
        public string R_Contact { get; set; }
        public System.DateTime R_Dateofbirth { get; set; }
        public string R_City { get; set; }
        public string R_Address { get; set; }
        public System.DateTime R_AddedOn { get; set; }
        public string R_Password { get; set; }
    }
}
